version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.6

jobs:
  build:
    docker:
      - image: circleci/node:15
    steps:
      - checkout
      - run:
          name: 💉Install dependencies
          command: |
            npm install
      - run:
          name: 🩺 Check lint
          command: |
            npm run lint:prettier
      - run:
          name: 🌡 Run test
          command: |
            npm run test:ci
      - coveralls/upload
